/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author umrmaulana
 */
public class FrmMenuKasir extends javax.swing.JFrame {
    koneksi k;

    /**
     * Creates new form FrmMenuKasir
     */
    public FrmMenuKasir() {
        initComponents();
        k = new koneksi();
        tampilIcon();
    }
    
    public void run() {
        // Membuat form maksimal
        FrmMenuUtama maks = new FrmMenuUtama();
        maks.setExtendedState(JFrame.MAXIMIZED_BOTH);
        maks.setVisible(true);
    }
    
    private void tampilIcon() {
        mnuFile.setIcon(loadIcon("./gambar/File_64x64.png", 64, 64));
        mnuTransaksi.setIcon(loadIcon("./gambar/Shopping_64x64.png", 64, 64));
        mnuAbout.setIcon(loadIcon("./gambar/About_64x64.png", 64, 64));
        mnuLogout.setIcon(new ImageIcon("./gambar/LogOut_16x16.png"));
        mnuKeluar.setIcon(new ImageIcon("./gambar/Keluar_16x16.png"));
        mnuPenjualan.setIcon(new ImageIcon("./gambar/Penjualan_16x16.png"));
        mnuPembelian.setIcon(new ImageIcon("./gambar/Pembelian_16x16.png"));
    }
    
    private ImageIcon loadIcon(String path, int width, int height) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mnuPenjualan = new javax.swing.JMenuItem();
        mnuPembelian = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: Menu Kasir :.");

        mnuFile.setText("File");
        mnuFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuFile.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mnuFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(mnuLogout);

        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        jMenuBar1.add(mnuFile);

        mnuTransaksi.setText("Transaksi");
        mnuTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuTransaksi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mnuTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTransaksiActionPerformed(evt);
            }
        });

        mnuPenjualan.setText("Penjualan");
        mnuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPenjualanActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuPenjualan);

        mnuPembelian.setText("Pembelian");
        mnuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPembelianActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuPembelian);

        jMenuBar1.add(mnuTransaksi);

        mnuAbout.setText("About");
        mnuAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuAbout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mnuAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuKeluarActionPerformed

    private void mnuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPenjualanActionPerformed
        // TODO add your handling code here:
        new FrmPenjualan().setVisible(true);
    }//GEN-LAST:event_mnuPenjualanActionPerformed

    private void mnuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPembelianActionPerformed
        // TODO add your handling code here:
        new FrmPembelian().setVisible(true);
    }//GEN-LAST:event_mnuPembelianActionPerformed

    private void mnuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuTransaksiActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuItem mnuPembelian;
    private javax.swing.JMenuItem mnuPenjualan;
    private javax.swing.JMenu mnuTransaksi;
    // End of variables declaration//GEN-END:variables
}
